-- Deshabilitar RLS para las tablas de Django
ALTER TABLE auth_user DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_group DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_group_permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_permission DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_user_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_user_user_permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE django_admin_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE django_content_type DISABLE ROW LEVEL SECURITY;
ALTER TABLE django_migrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE django_session DISABLE ROW LEVEL SECURITY;

-- Deshabilitar RLS para nuestras tablas personalizadas
ALTER TABLE authentication_user DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects_project DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects_projectmember DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks_task DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks_taskcomment DISABLE ROW LEVEL SECURITY;
