SHELL := /bin/bash

run:
	bash -c "source venv/bin/activate && python3 manage.py runserver"

migrate:
	bash -c "source venv/bin/activate && python3 manage.py migrate"

shell:
	bash -c "source venv/bin/activate && python3 manage.py shell"

install:
	bash -c "source venv/bin/activate && pip install -r requirements.txt"
